/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.vanier.ueps.ui;

import edu.vanier.ueps.simulations.controller.Controller;
import java.net.URL;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class MainApp extends Application {
    
    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/fxml.mainApp_1.fxml"));
        
        loader.setController(new Controller());
        
        Pane root = loader.load();
        
        Scene scene = new Scene(root);
        Image img = new Image("/image/logo.jpg");
        
        primaryStage.getIcons().add(img);
        primaryStage.setScene(scene);
        primaryStage.sizeToScene();
        primaryStage.setResizable(false);
        primaryStage.show();    
    }
    
    public static void main(String[] args) {
        launch(args);
    }
}
